# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prices', models.CharField(blank=True, choices=[('Small 12"', '1'), ('Medium 14"', '2')], max_length=4, null=True)),
            ],
        ),
    ]
