# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170107_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Gourmet Pizzas', 'Gourmet Pizza'), ('Appetizers', 'Appetizer'), ('Wings', 'Wings'), ('Salads', 'Salad'), ('Soups', 'Soup'), ('Calzones', 'Calzone'), ('Strombolis', 'Stromboli'), ('Grinders', 'Grinder'), ('Wraps', 'Wrap'), ('Pasta Dishes', 'Pasta'), ('Entrees', 'Entree'), ('Desserts', 'Dessert'), ('Extras', 'Extra'), ('Beverages', 'Beverage')], default='Pizza', max_length=15),
        ),
    ]
