# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
