# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170107_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
