# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170109_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='size',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
